### ISSUE TITLE
@pika/plugin-simple-bin lets me do the wrong thing

### ISSUE THREAD

**Issue by freethejazz** [pikapkg/builders#13]
This is a silly issue name so feel free to rename, but it is at least accurate: `plugin-simple-bin` will happily build a binary that will fail at runtime if the `index.js` file does not export `run`, `cli` or have a default export. The runtime error is a `TypeError: run is not a function`. We could improve this error message for troubleshooting purposes, but we should ideally catch this issue earlier. See #12 for a possible implementation.

**Comment by FredKSchott** [comment]
+1, looking forward to checking out the PR! Completely agreed that it shouldn't be so easy to do the wrong thing

**Comment by FredKSchott** [comment]
Update: A solution was merged in to check for these functions by evaluating the module, which is simple but may cause issues if the package has side effects (if it contains logic that can fail when loaded).

A better solution may be to run some regex on the `dist-src/index.js` file to collect all exports.

**Comment by ndom91** [comment]
@FredKSchott 

Im currently building a little `create-react-app` like node cli tool to output a Preact + Typescript + Pika starter project, but am having trouble with this. I have a check for passing in a project name as argument 1 to the cli, but when it gets called in the build process it obviously does not pass in any arguments and fails..

Can you elaborate a bit more on the regex check you mentioned? 

[ndom91/create-pika-app](https://github.com/ndom91/create-pika-app)

**Comment by FredKSchott** [comment]
Sure thing, the check is here: https://github.com/pikapkg/builders/blob/master/packages/plugin-simple-bin/src/index.js#L23-L26

This is really cool! You may not even need @pika/pack for this, since that's more a tool for package creators. If all you're building is a web app, you shouldn't need @pika/pack or any builders.

I'd love to see this example working so that I can share it with people, let me know if there's anything else I can help with!

Closing this since it looks like we fixed the original issue, but feel free to keep talking here or spin up any new issues on @pika/web.

**Comment by ndom91** [comment]
@FredKSchott yeah so theres two distinct things im working on here, 1) [ndom91/terminal-homepage](https://github.com/ndom91/terminal-homepage) which is just a little test website type thing that I would be happy to add to the examples page. 

2) [ndom91/create-pika-app](https://github.com/ndom91/create-pika-app) is supposed to be a create-react-app like node cli package. 

I realize @pika/pack doesnt make sense for 1, but packaging up 2 into a cli with this builder, for example, makes sense right?

**Comment by FredKSchott** [comment]
Yes! Gotcha, thanks for clarifying
