### ISSUE TITLE
web builder does not emit sourcemaps (?)

### ISSUE THREAD

**Issue by davibe** [pikapkg/builders#26]

**Comment by sant123** [comment]
Seems it only works with inline sourcemaps. Take a look at this .babelrc file:

``` json
{
  "sourceMaps": "inline"
}
```

**Comment by davibe** [comment]
`.babelrc` does not have any effect.

I was able to generate sourcemaps by adding a `rollup()` parameter: `sourcemap: true` right here https://github.com/pikapkg/builders/blob/master/packages/plugin-build-web/src/index.ts#L60

The problem now is that the source maps are referring to `pkg/dist-src` and not my real sources `src/index.ts`. This breaks for example visual studio code debugging.

**Comment by FredKSchott** [comment]
+1, we should add `sourcemap: true` to be the default behavior for all rollup-powered builders (web, node, etc).

**Comment by backspaces** [comment]
I would love an option to not generate source maps for pika/web. I have to delete them!

**Comment by bendtherules** [comment]
Any updates on this?

Sourcemaps are an important part of any build tool - to play nice with other existing tools. For ex., test coverage tools will show lower test coverage after pika build, just because they can't find or map back to the original files.

Would love to contribute this, if there is some official consensus.

**Comment by FredKSchott** [comment]
Support was just added, and will go out with the next `v0.6.0` release. We'll also be turning sourcemaps on by default, since they don't affect build-time and are important to many consumers. Thanks everyone for your patience on this!
