### ISSUE TITLE
Package not found error

### ISSUE THREAD

**Issue by williamtstanley** [pikapkg/builders#6]
I installed pika globally and then the standard-pkg as `npm install @pika/plugin-standard-pkg --save-dev`
However when running the pack build command I get the following error.
```
@pika/pack build v0.3.1
[1/4] Validating source...
[2/4] Preparing pipeline...
      ❇️  pkg/
[3/4] Running undefined...
Error: Command failed.
Exit code: 127
Command: @pika/plugin-standard-pkg
Arguments: 
Directory: /home/<user>/Development/<project>/component-library
Output:
/bin/sh: 1: @pika/plugin-standard-pkg: not found
```
This is the pika section of my package.json

```
"@pika/pack": {
    "pipeline": [
      "@pika/plugin-standard-pkg",
      {
        "exclude": [
          "**/*.test.js",
          "**/*.stories.js",
          "__mocks__/*"
        ]
      }
    ]
  },
```
If anyone can point me to a fix I would appreciate it.

**Comment by FredKSchott** [comment]
Make sure you put each plugin in an array, your pipeline would instead look like:

```
"@pika/pack": {
    "pipeline": [
      ["@pika/plugin-standard-pkg", {
        "exclude": [
          "**/*.test.js",
          "**/*.stories.js",
          "__mocks__/*"
      ]}]
    ]
},
```

**Comment by williamtstanley** [comment]
Absolutely that was my error. Thank you. Now to figure out how to get styles to not crash it with:
```
SyntaxError: /home/travis/Development/fitplan/component-library/src/config/variables.css: Unexpected token (1:0)

> 1 | :root {
    | ^
  2 |   --black: #111213;
  3 |   --flat-green-bright-bg: #12b587;
  4 |   --flat-green-dark-bg: #00ffb3;
```

**Comment by FredKSchott** [comment]
Hmm, does this repo exist anywhere I could check it out? I'm surprised it's outright failing, that could be happening inside of Rollup.

In general, importing CSS from inside of JS isn't allowed on any JS platform. Bundlers allow it as a convenient shortcut (I've done this in plenty of apps I've built, and it's great). But since you're publishing to a shared NPM registry where you don't know who your consumer is, I'd recommend keeping it outside of your JS if you can.

We recommend an `assets/` directory for non-JS assets that would be shared across different distributions of your package. My # 1 todo right now is to document all of this, which didn't make it into that first blog post :)

**Comment by paul-pro** [comment]
@FredKSchott, can you provide some examples of importing css with pika build?

**Comment by FredKSchott** [comment]
I will try to add one to https://github.com/pikapkg/examples, if no one else beats me to it :)

**Comment by FredKSchott** [comment]
I was never able to find the time for this, but here's the basic steps:
- put your CSS in a top-level assets/ dir
- make sure you have this plugin in your build pipeline https://github.com/pikapkg/builders/tree/master/packages/plugin-copy-assets
- If you only care about your package working when consumed with a bundler, just `import '../assets/my.css'` inside of your src directory
- If you want to target direct usage, you'll want to do some special logic to add a `<style>`/`<link>` tag to the page via JavaScript that will load your CSS file.
